---
name: handle-pr-approval
run-name: "Handle PR review for PR #${{ github.event.pull_request.number }}"

on:
  pull_request_review:
    types:
      - submitted

jobs:
  handle-pr-approval:
    name: Handle PR approval
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Add random meme
        uses: ChainReaction-LTD/approved-pr-random-meme@v1
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check for GitHub CLI
        run: |
          if ! command -v gh &> /dev/null; then
            echo "[INFO] GitHub CLI not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y gh
            echo "[INFO] GitHub CLI installed successfully"
          else
            echo "[INFO] GitHub CLI is already installed"
          fi

      - name: Github's auto squash merge for Dependabot PRs
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        shell: bash
        run: |
          # Initialize status
          status="success"

          # Function to post a comment on the PR
          post_comment() {
            local reason="$1"
            # Comment about failure
            local COMMENT_BODY="{\"body\": \"@ChainReaction-LTD/devops squash and merge failed, $reason\"}"
            curl -fSsL \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "$COMMENT_BODY" \
              "${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          }
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "[INFO] Enabling auto-merge (squash) for Dependabot PR #$PR_NUMBER via gh CLI"
          export GH_TOKEN="${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          if ! gh pr merge "$PR_NUMBER" --repo "${{ github.repository }}" --squash --auto; then
            echo "[ERROR] gh CLI auto-merge request failed"
            status="failed"
            reason="gh pr merge --auto failed"
          fi

          # if final status is failed, post a comment
          if [[ "$status" == "failed" ]]; then
            post_comment "$reason"
          fi
