---
name: handle-pr-approval
run-name: "Handle PR review for PR #${{ github.event.pull_request.number }}"

on:
  pull_request_review:
    types:
      - submitted

jobs:
  handle-pr-approval:
    name: Handle PR approval
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add random meme
        uses: ChainReaction-LTD/approved-pr-random-meme@v1
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Dependabot squash and merge
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        shell: bash
        run: |
          curl -fSsL \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{\"body\": \"@dependabot squash and merge\"}" \
            "${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
